### ISSUE TITLE
Part 4. Depth and odometry

### ISSUE THREAD

**Issue by xiongdemao** [Huangying-Zhan/Depth-VO-Feat#1]
thanks for your release code!
wen i run the fellow code with Part 3. Depth
```
Run bash ./expriments/depth/train.sh.
```
it happen some error ：
```
 29274 layer_factory.hpp:77] Creating layer geoTransform
F0402 17:17:15.390364 29274 layer_factory.hpp:81] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: GeoTransform (known types: AbsVal, Accuracy, ArgMax, BNLL, BatchNorm, BatchReindex, Bias, Concat, ContrastiveLoss, Convolution, Crop, Data, Deconvolution, Dropout, DummyData, ELU, Eltwise, Embed, EuclideanLoss, Exp, Filter, Flatten, HDF5Data, HDF5Output, HingeLoss, Im2col, ImageData, InfogainLoss, InnerProduct, Input, LRN, LSTM, LSTMUnit, Log, MVN, MemoryData, MultinomialLogisticLoss, PReLU, Parameter, Pooling, Power, Python, RNN, ReLU, Reduction, Reshape, SPP, Scale, Sigmoid, SigmoidCrossEntropyLoss, Silence, Slice, Softmax, SoftmaxWithLoss, Split, TanH, Threshold, Tile, WindowData)
*** Check failure stack trace: ***
    @     0x7f53f519f5cd  google::LogMessage::Fail()
    @     0x7f53f51a1433  google::LogMessage::SendToLog()
    @     0x7f53f519f15b  google::LogMessage::Flush()
    @     0x7f53f51a1e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f53f583f794  caffe::Net<>::Init()
    @     0x7f53f5840bae  caffe::Net<>::Net()
    @     0x7f53f5849d05  caffe::Solver<>::InitTrainNet()
    @     0x7f53f584b175  caffe::Solver<>::Init()
    @     0x7f53f584b48f  caffe::Solver<>::Solver()
    @     0x7f53f585c961  caffe::Creator_AdamSolver<>()
    @           0x40bd63  train()
    @           0x408480  main
    @     0x7f53f3e7d830  __libc_start_main
    @           0x408ca9  _start
    @              (nil)  (unknown)
```
by the way ，can i have a question about how to “Remember to enable Python Layers in the Caffe configuration.” in ”Part 1. Requirements“

**Comment by Huangying-Zhan** [comment]
Hi @xiongdemao , For the python layer issue, I mean that you need to uncomment "WITH_PYTHON_LAYER := 1" in your Makefile.config to enable Python Layers. Here is an example of Caffe's python layer usage: https://github.com/NVIDIA/DIGITS/tree/master/examples/python-layer

For the error related to "GeoTransform" layer, it looks like you haven't added the caffe layers provided in this repo to your caffe. Please add my provided layers into your caffe and complile again and tell me if there is further problem.

**Comment by xiongdemao** [comment]
add
```
optional GeoTransformParameter pin_hole_param = 147;
...
message GeoTransformParameter {
}
```
in caffe.proto. like this,is not anthing in the 
```
message GeoTransformParameter {
}
```
?

**Comment by Huangying-Zhan** [comment]
@xiongdemao you don't need to add the layers in caffe.proto since the layers do not contain parameters (e.g. in Conv layer, you need to specify strides / filter size). I mean you need to put my layers (.cu & .cpp) in your "caffe/src/caffe/layers/" and .hpp files in "caffe/include/caffe/layers/". Just like the directory I used in this repo. After putting the layers in your Caffe. You need to recompile the caffe such that the layers can be used.

**Comment by xiongdemao** [comment]
oh!that's ok,thank you!
