### ISSUE TITLE
get depth-prediction

### ISSUE THREAD

**Issue by WZYSilverWing** [Huangying-Zhan/Depth-VO-Feat#10]
![0](https://user-images.githubusercontent.com/23632462/39952427-26105c0a-55c9-11e8-9c62-6f57026dfd8b.png)

Sorry to bother you. How to solve this when run the depth evaluation? Thank you!

**Comment by Huangying-Zhan** [comment]
Hi @WZYSilverWing , I think it is because of the incorrect `img_path`. Please check the `img_path`. I will update my code to have a warning regarding the issue.

Just updated the `tools/evaluation_tools.py`. Please try again the evaluation

**Comment by WZYSilverWing** [comment]
Solved. Thank U so much.
