### ISSUE TITLE
about plot error

### ISSUE THREAD

**Issue by WZYSilverWing** [Huangying-Zhan/Depth-VO-Feat#12]
I want to draw the plot error figure, but when I use the evaluation_tool, it turns out to be like this, how to solve this? thank you!
![0](https://user-images.githubusercontent.com/23632462/40034360-2ecc618c-582f-11e8-9993-a21d8e7f0e8b.png)

**Comment by Huangying-Zhan** [comment]
Hi @WZYSilverWing, the plot_error function is not really ready to use. 
However, as you can see that, there is `IndexError`, it is about accessing `avg_segment_errs[lens_][0]`. Could you try to print out avg_segment_errs for this sequence? I guess there is something wrong with the `avg_segment_errs`. It might be empty in your case.

**Comment by WZYSilverWing** [comment]
OK, I'll try it. Thank you!
