### ISSUE TITLE
About back-propagation of geometry transformation layer

### ISSUE THREAD

**Issue by JingyuChan** [Huangying-Zhan/Depth-VO-Feat#13]
I have a question about the back-propagation process in the geometry transformation layer. The derivative dX_dD in line 111 in geometry_transformation.cu is wrote as "dX_dD = trans_off[0] * base_X + trans_off[1] * base_Y + trans_off[2]". In my opinion, "X = trans_off[0] * base_X + trans_off[1] * base_Y + trans_off[2] * D + trans_off[3]", so the derivative of D is "dX_dD = trans_off[2]". Since the derivative is took of D, "trans_off[0] * base_X + trans_off[1] * base_Y" should be regarded as constant, which is the same as the "trans_off[2]". Thus I think the expression of dX_dD shouldn't contain the "trans_off[0] * base_X + trans_off[1] * base_Y". This may be my misunderstanding, could you please explain this for me? Thanks a lot!

**Comment by Huangying-Zhan** [comment]
Hi @JingyuChan, Thanks for your question. 
transformed_X 
= trans_off[0] * old_X + trans_off[1] * old_Y + trans_off[2] * old_Z + trans_off[3]
= trans_off[0] * (base_X * D) + trans_off[1] * (base_Y * D)  + trans_off[2] * D + trans_off[3]
where,
old_X = [(x-c_x)/f_x] * D = base_X * D
old_Y = [(y-c_y)/f_y] * D = base_Y * D

Therefore, d(transformed_X)/d(D) = trans_off[0] * (base_X ) + trans_off[1] * (base_Y )  + trans_off[2] 

Please let me know if there is any further problem.

**Comment by JingyuChan** [comment]
@Huangying-Zhan Thank you so much! I made a mistake to neglect the difference between base_X and old_X. And I'm sorry to bother you with my careless. Thanks again for solving my problem!

**Comment by Huangying-Zhan** [comment]
@JingyuChan No worries. That could also be my problem as well. I didn't make too much comment on my script.
