### ISSUE TITLE
when i run the comand “make runtest”,i meet this error, i have added the required layers in ./caffe into my own Caffe

### ISSUE THREAD

**Issue by hyaihjq** [Huangying-Zhan/Depth-VO-Feat#14]
F0708 06:35:00.978440 12323 blob.hpp:140] Check failed: num_axes() <= 4 (5 vs. 4) Cannot use legacy accessors on Blobs with > 4 axes.
*** Check failure stack trace: ***
    @     0x7f0be45ab5cd  google::LogMessage::Fail()
    @     0x7f0be45ad433  google::LogMessage::SendToLog()
    @     0x7f0be45ab15b  google::LogMessage::Flush()
    @     0x7f0be45ade1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x490d41  caffe::Blob<>::LegacyShape()
    @           0x77a9dc  caffe::PositiveUnitballFiller<>::Fill()
    @           0x8f1a90  caffe::PositiveUnitballFillerTest<>::test_params()
    @           0x8eb5ee  caffe::PositiveUnitballFillerTest_TestFill5D_Test<>::TestBody()
    @           0x955973  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x94ef8a  testing::Test::Run()
    @           0x94f0d8  testing::TestInfo::Run()
    @           0x94f1b5  testing::TestCase::Run()
    @           0x95048f  testing::internal::UnitTestImpl::RunAllTests()
    @           0x9507b3  testing::UnitTest::Run()
    @           0x47123d  main
    @     0x7f0be10bc830  __libc_start_main
    @           0x4792e9  _start
    @              (nil)  (unknown)
Makefile:533: recipe for target 'runtest' failed
make: *** [runtest] Aborted (core dumped)

**Comment by Huangying-Zhan** [comment]
Hi @hyaihjq, could you provide more details about this error? It seems the number of axes is not correct but I don't know which layer caused this problem.

**Comment by hyaihjq** [comment]
don‘t  add the file "filter.hpp" into caffe, can successfully complete the caffe’compilation. but add the file "filter.hpp" into caffe encounter this error.

**Comment by hyaihjq** [comment]
but don‘t add the file "filter.hpp" into caffe, i can‘t train the code

**Comment by hyaihjq** [comment]
src/caffe/test/test_filler.cpp:524: Failure
The difference between expected_value and actual_value is 0.078125, which exceeds 0.01, where
expected_value evaluates to 0.0625,
actual_value evaluates to 0.140625, and
0.01 evaluates to 0.01.
[  FAILED  ] BilinearFillerTest/0.TestFillOdd, where TypeParam = float (44368 ms

**Comment by Huangying-Zhan** [comment]
If the problem is with filler.hpp. You can just add the part related to "EdgeX" and "EdgeY" into your original filler.hpp.

**Comment by hyaihjq** [comment]
i have solved this problem，the new version caffe‘s filler.hpp have some changed. thanks for your help!!!

**Comment by Huangying-Zhan** [comment]
@hyaihjq, I see. Could you share the solution that you solve this problem in case other users have the same problem in the future? Thank you!

**Comment by hyaihjq** [comment]
download this caffe old version “https://github.com/BVLC/caffe/releases/tag/1.0”

**Comment by hyaihjq** [comment]
or adopt your suggest "You can just add the part related to "EdgeX" and "EdgeY" into your original filler.hpp."
