### ISSUE TITLE
how to visualize the disparity map

### ISSUE THREAD

**Issue by lraxue** [Huangying-Zhan/Depth-VO-Feat#15]
Could you please tell me how to visualize the 1-channel disparity map as 3-channel color image?

**Comment by Huangying-Zhan** [comment]
@lraxue Sorry for the late reply! There are different ways to do it in Python (e.g. matplotlib / OpenCV)
If you want to visualize it via matplotlib, here is the way I usually do.
```
from matplotlib import pyplot as plt
plt.imshow(depth, cmap="plasma")
plt.show()
```

For cmap, there are many options, please refer to here:
https://matplotlib.org/tutorials/colors/colormaps.html

Hope it helps!
