### ISSUE TITLE
need gpu for running

### ISSUE THREAD

**Issue by amira133** [Huangying-Zhan/Depth-VO-Feat#17]
hello

I have a question :
Do you need GPU to run your application?
if yes what is min of GPU?

**Comment by Huangying-Zhan** [comment]
Hi @amira133 , yes, the training requires a GPU. Otherwise, it will take a long time to train with a CPU.
Any GPU with sufficient memory should be fine. The one I am using is GTX1070Ti.

**Comment by amira133** [comment]
@Huangying-Zhan I have another question : How much time does it take with your GPU (GTX1070Ti)?

**Comment by Huangying-Zhan** [comment]
@amira133 For each experiment, it is about 1 day.

**Comment by amira133** [comment]
thanks
