### ISSUE TITLE
when I run evaluation_tools.py to generate_depth_npy, has error"target_blobs.size() == source_layer.blobs_size() (5 vs. 3) Incompat              ible number of blobs for layer bn_1"

### ISSUE THREAD

**Issue by lvhualong** [Huangying-Zhan/Depth-VO-Feat#20]
when I run evaluation_tools.py to generate_depth_npy, 
has error"target_blobs.size() == source_layer.blobs_size() (5 vs. 3)
 Incompatible number of blobs for layer bn_1"

so I commented all the "BatchNorm" layer of depth_deploy.prototxt, the python code can run ,but the depth maps error

![2018-12-13 19 21 55](https://user-images.githubusercontent.com/26672004/49935582-5d9c1280-ff0c-11e8-9f92-1dfdf6381e74.jpg)

**Comment by Huangying-Zhan** [comment]
Hi @Sunshinehualong, I am not sure about the reason at the moment. Could you give more information? Could you also check the shape of your input data?

**Comment by lvhualong** [comment]
At first, I thought there was something wrong with my input data ,
 but later I changed it to KITTI image for  test, and it's still this case.


I saw the file of experiments//experiments/depth/train.prototxt , all the  BatchNorm layer with use_global_stats: false

![image](https://user-images.githubusercontent.com/26672004/49991353-c55d6680-ffbb-11e8-9aad-7001666ad183.png)


while the file experiments/networks/depth_deploy.prototxt, all the  BatchNorm layer with use_global_stats: true

![image](https://user-images.githubusercontent.com/26672004/49991444-08b7d500-ffbc-11e8-9aeb-83feeae13fff.png)

I didn't retrain the network for myself, just use  your trained models (Baseline.caffemodel  KITTI_Feat.caffemodel  Temporal.caffemodel)
So I'm not sure whether or not you use the BatchNorm when you  training the net.

**Comment by lvhualong** [comment]
Here are my test results when remove all the BatchNorm layer of networks/depth_deploy.prototxt

![output_0](https://user-images.githubusercontent.com/26672004/49991952-9811b800-ffbd-11e8-977f-d91ba7709fe6.png)
![output_1](https://user-images.githubusercontent.com/26672004/49991953-9811b800-ffbd-11e8-9df2-c8e836fd82f0.png)

**Comment by Huangying-Zhan** [comment]
Hi @Sunshinehualong , I use BN in the training time. For BN layer, usually, we set `use_global_stats` to be `False` in  training time so it only uses batch statistics. During training, BN layer also compute global statistics and the global statistics are used in testing time, so you see that `use_global_stats` is `True` in the deploy.prototxt. 

Please check the following issue.
https://devtalk.nvidia.com/default/topic/1029725/gpu-accelerated-libraries/nvcaffes-batchnormlayer-is-incompatible-with-bvlc-caffe/
The post suggests that different Caffe Version is using different BN implementations which has different size of blobs. Could you try to check if this is the issue?

**Comment by Huangying-Zhan** [comment]
Closed because of no update.
Open when there is a further update.
