### ISSUE TITLE
No register converter error occured when running the Python Layer('SE3') in odometry_deploy.prototxt

### ISSUE THREAD

**Issue by UltronAI** [Huangying-Zhan/Depth-VO-Feat#21]
Error info:

Traceback (most recent call last):
    File "compare.py", line 110, in main
        odom_net.forward()
    File "/home/gaof/caffe-dev/python/caffe/pycaffe.py", line 121, in _Net_forward
        self._forward(start_ind, end_ind)
    File "/home/gaof/caffe-dev/python/pygeometry.py", line 33, in forward
        self.uw = bottom[0].data[:,:3] 
TypeError: No registered converter was able to produce a C++ rvalue of type std::shared_ptr<caffe::Blob<float> > from this Python object of type Blob

__Note that I have copied files in ./caffe into my own caffe and recompiled it.__

How can I fix this bug? Did anyone else encounter this problem as well?

**Comment by Huangying-Zhan** [comment]
Hi @UltronAI , I didn't encounter this problem before.
Here are a few things you may check.
(1) Have you enabled Python layer in your Makefile.config?
(2) Could you check the input data `bottom[0].data[:,:3]` to ensure it is has the correct format/shape?

**Comment by UltronAI** [comment]
Thanks for your prompt reply. @Huangying-Zhan 
I have enabled Python Layer in Makefile.config, and this error occurred when calling `bottom[0].data`.
Some issues in other github repos said that it's related to boost. My boost version is 1.58 on ubuntu16.04, which should be right in my opinion... 
I don't know why I can't run Python Layer ...

**Comment by Huangying-Zhan** [comment]
Hi @UltronAI, have you solved the problem?

**Comment by UltronAI** [comment]
@Huangying-Zhan Yes, I reinstall the caffe and Python layer can work well now. But I still don't know where the error is.

**Comment by UltronAI** [comment]
Not solved. If someone has the same problem, please reopen this issue and tell me how to solve it.
