### ISSUE TITLE
pretrained model in dropbox can't  download

### ISSUE THREAD

**Issue by xiaomaicha** [Huangying-Zhan/Depth-VO-Feat#22]
Thank you for your code, I want to use your pre-training model to test some results, I entered the Dropbox page to download the model, but I can't download it.Maybe there is something wrong with the website. Do you have other addresses for storing the model, such as Google Cloud Drive, thank you very much!
> 
![image](https://user-images.githubusercontent.com/31534343/50288229-46c36600-04a0-11e9-9a98-01294eee5afd.png)

**Comment by Huangying-Zhan** [comment]
Hi @xiaomaicha , I just tried again and it can be downloaded. Could you provide more information about the issue? If you click on the file, can you see this page?
![image](https://user-images.githubusercontent.com/13748721/50316302-fbdc3980-0505-11e9-8333-195fdf044543.png)

**Comment by xiaomaicha** [comment]
I can access this page and click on download, and then I've been waiting for the connection, and then there's no response. Perhaps the use of Dropbox in China is limited during this period? I'd like to use  temporal.caffemodel in odometry_split. Could you please send  this model to my mail 240191740@qq.com? Thank you very much!

![image](https://user-images.githubusercontent.com/31534343/50319615-3b555680-0503-11e9-8f5c-1a2c0d397ba7.png)

**Comment by Huangying-Zhan** [comment]
Hi @xiaomaicha , I tried to send it via email but the file is too large and it didn't work. I have uploaded the model to BaiduPan. Please check the following link and let me know if you can download the model.
https://pan.baidu.com/s/1ssuHdQZX39RRMVfO7BEvpA

**Comment by xiaomaicha** [comment]
> Hi @xiaomaicha , I tried to send it via email but the file is too large and it didn't work. I have uploaded the model to BaiduPan. Please check the following link and let me know if you can download the model.
> https://pan.baidu.com/s/1ssuHdQZX39RRMVfO7BEvpA
Yes, I can download it. Thank you very much！

**Comment by xiaomaicha** [comment]
Yes, I can download it. Thank you very much！
