### ISSUE TITLE
Something Wrong with the odometry result.

### ISSUE THREAD

**Issue by lixiangyu-1008** [Huangying-Zhan/Depth-VO-Feat#23]
hi @Huangying-Zhan 
thanks for your work!
when I the run odometry results you released, the ORB-SLAM odometry plot track path was wrong with the Ground Truth. 
![sequence_10](https://user-images.githubusercontent.com/33485373/54470635-2af10700-47e6-11e9-9b17-ab011e0531ef.png)
Do you know why?

**Comment by Huangying-Zhan** [comment]
Hi @lixiangyu-1008 , the first ~30 frames are used for initialization in ORB-SLAM so you can found that the first ~30 poses are missing there. You need to align the poses after that with the GT or ignore GT's first ~30  poses.

**Comment by lixiangyu-1008** [comment]
hi @Huangying-Zhan thanks for replying!

1. I try to do as you said to “ignore GT's first ~30 poses”， I delete the first ~30 lines poses of GT Poses.txt and then plot the path, the Seq10 path is also the same as the previous, it seems nothing change, maybe I misunderstanding you said?

2. Another suggestions you said **You need to align the poses after that with the GT**, I don't how to  align the poses.

**Comment by Huangying-Zhan** [comment]
1. after ignoring GT's first 30 poses, I think you need to transform your GT poses w.r.t 31st pose (i.e. make 31st pose is the initial pose in both ORB-SLAM & GT) 
2. use GT's 31st pose as the initial pose for ORB-SLAM and transform ORB-SLAM poses.

**Comment by lixiangyu-1008** [comment]
@Huangying-Zhan 

1. Thanks for your answer, I transform the GT's 31st pose as the initial pose,and then the plot path was right as you paper.

2.Another question why you said  **trying (1) will be fair in the evaluation.**, you means transform the GT's pose will be fair?

**Comment by Huangying-Zhan** [comment]
@lixiangyu-1008 sorry about that, I made a wrong statement. Both approaches are fair as long as you evaluate the result since 31st pose.
