### ISSUE TITLE
F0418 21:31:37.329504 11665 image_data_layer.cpp:49] Check failed: !lines_.empty() File is empty

### ISSUE THREAD

**Issue by kourong** [Huangying-Zhan/Depth-VO-Feat#24]

**Comment by Huangying-Zhan** [comment]
Hi @kourong, could you provide more detail about the error? 
Also, could you double check the training set you are using? Are you providing a correct path of the txt file?

**Comment by kourong** [comment]
hello,when i run steo 3 bash ./expriments/depth/train.sh,i get a error

![WechatIMG169](https://user-images.githubusercontent.com/34885093/56403863-f2859280-6295-11e9-892a-d2328561f983.png)
can you help me ?

**Comment by Huangying-Zhan** [comment]
could you check `./data/dataset/kitti_eigen/train_left_1.txt` to see if the file is there and also the file is not empty?

**Comment by kourong** [comment]
> could you check `./data/dataset/kitti_eigen/train_left_1.txt` to see if the file is there and also the file is not empty?

**Comment by kourong** [comment]
@Huangying-Zhan  Thank you ，I have solved the above problem，but there are new problems，can you help me ?
And --gpu:command not found ,why? I am using a gpu machine
![Screenshot from 2019-04-20 12-06-23](https://user-images.githubusercontent.com/34885093/56452634-b457a400-6365-11e9-83d8-5580532f9ab8.png)
