### ISSUE TITLE
Hello,when i run ./experiments/depth/train.sh ,it occur a error : no module named pygeometry,but i try import geometry,it works.And i am sure i install PyGeometry module 

### ISSUE THREAD

**Issue by kourong** [Huangying-Zhan/Depth-VO-Feat#25]

**Comment by Huangying-Zhan** [comment]
Can you try to include `caffe/python` in your PYTHONPATH?

**Comment by kourong** [comment]
> Can you try to include `caffe/python` in your PYTHONPATH?

Yes,I include caffe/python in my ~/.bashrc,but it's doesn't work.
![Screenshot from 2019-05-05 14-18-16](https://user-images.githubusercontent.com/34885093/57189407-050ff500-6f41-11e9-84a0-dd9d749d6490.png)
