### ISSUE TITLE
about trajectories plot

### ISSUE THREAD

**Issue by sunnyHelen** [Huangying-Zhan/Depth-VO-Feat#27]
It's so kind of you to provide not only your pose result but also other methods' result, like ORBslam.
![image](https://user-images.githubusercontent.com/28101548/60774905-8280fd00-a15e-11e9-941b-2a49038708b0.png)
I notice that you compare the result of SfMlearner's result. Could you please upload a file of it?

**Comment by Huangying-Zhan** [comment]
Hi @sunnyHelen , unfortunately, I have lost the original SfMlearner result and the code generating the result (maybe during a system upgrade or still existing somewhere in my PC).
There are some people asked for it and I couldn't find it.
However, I have re-written a new code and generated a new result for it.
Please check the dropbox. The new result should be there.

Also, the code is available here:
https://github.com/Huangying-Zhan/Depth-VO-Feat/tree/master/tools/sfmlearner_odometry_tool
To run the code, you have to download the SfMLearner pose result.
https://github.com/tinghuiz/SfMLearner#pose

Please note that somehow the new result is a little bit different from the result in the paper but the difference is insignificant.

**Original result** 
seq|  trans error | rot error |
09: 17.84; 6.78
10: 37.91; 17.78

**new result** (updated on 4/9/2019)
09: 17.81; 6.82
10: 38.49; 17.69

**Comment by sunnyHelen** [comment]
Thanks a million!
