### ISSUE TITLE
Training on odometry split

### ISSUE THREAD

**Issue by babyfisher** [Huangying-Zhan/Depth-VO-Feat#30]
Hi Zhan,
Can I use the given solver.prototxt for both Eigen-split based training and Odom-split based training? Is there any difference between them in terms of training parameters?

**Comment by babyfisher** [comment]
Would you like to share the part of kitti-sequence data preparation as well? (as you mentioned in your to-do list). Thank you in advance.

**Comment by Huangying-Zhan** [comment]
Hi @babyfisher, yes, I am happy to share but sorry that I was busy with other projects. I will try my best to share it soon.

**Comment by Huangying-Zhan** [comment]
Hi, I just added my previous odometry dataset builder into the current project. I did a simple test and it seems works fine. Please check if it works for you.
Please check this temporary branch.
https://github.com/Huangying-Zhan/Depth-VO-Feat/blob/kitti_odom_builder/data/dataset_builder.py

**Comment by babyfisher** [comment]
@Huangying-Zhan Thank you for your help!
