### ISSUE TITLE
Align the unsupervised methods results

### ISSUE THREAD

**Issue by lixiangyu-1008** [Huangying-Zhan/Depth-VO-Feat#31]
hi @Huangying-Zhan 

I have a question about how to align the results from sfmlearner with ground truth?
1) first, the result produce by sfmlearner are 5-frames, and all the pose ares relative to the middle frame, so you said in your paper that you align every 5 frames independently? 
2) could you share your code how to align with GT?

**Comment by Huangying-Zhan** [comment]
Hi @lixiangyu-1008 , I have released the tool that I used for converting sfmlearner result from 5-frames to a whole trajectory.
There are many ways to concatenate the predictions to form a whole trajectory and here is just one of the ways.
please check the following link.
https://github.com/Huangying-Zhan/Depth-VO-Feat/tree/master/tools/sfmlearner_odometry_tool

For visualizing sfmlearner result, I would recommend the following tool:
https://github.com/MichaelGrupp/evo

It is better to view the result in 3D, especially sequence 10. I notice that the 2D visualization in the paper looks weird to some people, including myself at the beginning. 
There is a rotation issue in the result and it can be found from the 3D visualization.

Note that, the sfmlearner result that we compared to was the result the authors released. 
Please check here
https://github.com/tinghuiz/SfMLearner/blob/master/kitti_eval/download_kitti_pose_eval_data.sh

We recently found that the updated model in SfMlearner give better result and we evaluate the result in one of our recent work. Please check here:
https://arxiv.org/abs/1909.09803

**Comment by lixiangyu-1008** [comment]
hi @Huangying-Zhan 
 
Thanks for you reply.
I will have a try!

**Comment by lixiangyu-1008** [comment]
@Huangying-Zhan 

could please share the pose results of sfmlearner？ Since the website of download link can not surf.
my email: lixiangyu_1008@163.com
thanks :)

**Comment by Huangying-Zhan** [comment]
here is the original link
http://people.eecs.berkeley.edu/~tinghuiz/projects/SfMLearner/pose_eval_data.tar

Please let me know if it doesn't work.

**Comment by lixiangyu-1008** [comment]
It's work now, maybe yesterday caused by the internet.
thank you!

**Comment by lixiangyu-1008** [comment]
hi  
I have change the SfMlearner to the full trajectory as you said.
but I use the evaluation code to evaluate the seq.9and 10 .the results are:

Sequence: 9
Average translational RMSE (%):  70.42703633858463
Average rotational error (deg/100m):  30.31412894682484
Sequence: 10
Average translational RMSE (%):  51.7403945088599
Average rotational error (deg/100m):  20.95954803583636
-------------------- For Copying ------------------------------

**Comment by Huangying-Zhan** [comment]
Hi, could you post the trajectory plot as well so I can have more clues about the result?

**Comment by lixiangyu-1008** [comment]
hi here is the trajectory and results:
**1. solve_global_pose = True:**
Sequence: 9
Average translational RMSE (%):  70.42703633858463
Average rotational error (deg/100m):  30.31412894682484
Sequence: 10
Average translational RMSE (%):  51.7403945088599
Average rotational error (deg/100m):  20.95954803583636
-------------------- For Copying ------------------------------
**trajectory:**
**seq.09:**
![sequence_09](https://user-images.githubusercontent.com/33485373/66710321-7ed9c380-eda8-11e9-80df-4b4c34c50e7e.png)
**seq.10:**
![sequence_10](https://user-images.githubusercontent.com/33485373/66710323-84cfa480-eda8-11e9-9dd3-46ba9b73204c.png)


**2.solve_global_pose = False:**
Sequence: 9
Average translational RMSE (%):  102.76902434117726
Average rotational error (deg/100m):  30.31412894682484
Sequence: 10
Average translational RMSE (%):  97.63435792829532
Average rotational error (deg/100m):  20.95954803583636
-------------------- For Copying ------------------------------
**seq.09:**
![sequence_09](https://user-images.githubusercontent.com/33485373/66710329-9dd85580-eda8-11e9-9b89-263020ecd56d.png)
**seq.10:**
![sequence_10](https://user-images.githubusercontent.com/33485373/66710331-a3ce3680-eda8-11e9-88e0-3beecaf400e9.png)

**Comment by Huangying-Zhan** [comment]
I haven't seen something like this before. 
If you have modified the tool, could you send me the modified version so I can take a look?

my email: huangying.zhan@adelaide.edu.au

Also, please send me the final trajectory files you got from those setups.
