### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by WZYSilverWing** [Huangying-Zhan/Depth-VO-Feat#6]
when running the depth train, meet this problem. what is pygeometry?
![0](https://user-images.githubusercontent.com/23632462/39706354-bd6b8f2c-5243-11e8-8645-f81c9245d434.png)

**Comment by Huangying-Zhan** [comment]
Hi @WZYSilverWing , you need to add the python layer into your caffe/python and also enable python layer in Makefile.config.
