### ISSUE TITLE
about Trajectories

### ISSUE THREAD

**Issue by WZYSilverWing** [Huangying-Zhan/Depth-VO-Feat#7]
I know it is a silly question, but after I trained the model and get the test output, how can I get the Trajectories? Thank you!

**Comment by Huangying-Zhan** [comment]
Hi @WZYSilverWing No worries! The idea in this work is a simple two-view relative camera pose estimation. Basically, you need to convert/accumulate the relative camera poses into camera poses in world coordinate system. The camera poses (under world coordinate system) form the trajectory. 
For implementation, you can refer to `kittiPredOdom.SE3_cam2world ()` in`tools/evaluation_tools.py`, which converts relative poses to world poses. Also, in the same file,  There is a class named `kittiEvalOdom`, which contains the code for drawing the trajectories.

**Comment by WZYSilverWing** [comment]
@Huangying-Zhan thank you!
