### ISSUE TITLE
when run ./experiments/depth_odometry_feature/train.sh

### ISSUE THREAD

**Issue by WZYSilverWing** [Huangying-Zhan/Depth-VO-Feat#8]
in ./experiments/depth_odometry_feature/train.sh, it requires Weerasekera_nyu.caffemodel, where can I dowload this caffe model? thank you!

**Comment by Huangying-Zhan** [comment]
Hi @WZYSilverWing , the model is not yet released. The model is trained from this paper, [Weerasekera et al.](https://arxiv.org/abs/1711.05919 ). I will post a link to the model later.
If you want to use the feature construction loss, please try the `KITTI_feat.caffemodel` for now. Sorry for the inconvenience caused.

**Comment by WZYSilverWing** [comment]
thank you so much!
